name: Pre-Commit

on:
  pull_request:
    branches:
      - main
      - master

env:
  ImageOS: ubuntu22
  TERRAFORM_DOCS_VERSION: v0.16.0
  TFLINT_VERSION: v0.64.0

jobs:
  collectInputs:
    name: Collect workflow inputs
    runs-on:
      - runs-on
      - runner=2cpu-linux-x64
      - "run-id=${{ github.run_id }}"
    outputs:
      directories: ${{ steps.dirs.outputs.directories }}
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2
        with:
          use-policy-store: true
          api-key: ${{ secrets.GH_FRESHAENGINEERING_STEP_SECURITY_API_KEY }}

      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Get root directories
        id: dirs
        uses: step-security/terraform-composite-actions/directories@2eac41b76974f2ae6fd8f1ad78d51eb3bdaed7b0 # v1.14.0

  preCommitMinVersions:
    name: Min TF pre-commit
    needs: collectInputs
    runs-on:
      - runs-on
      - runner=2cpu-linux-x64
      - "run-id=${{ github.run_id }}"
    strategy:
      matrix:
        directory: ${{ fromJson(needs.collectInputs.outputs.directories) }}
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2
        with:
          use-policy-store: true
          api-key: ${{ secrets.GH_FRESHAENGINEERING_STEP_SECURITY_API_KEY }}

      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Terraform min/max versions
        id: minMax
        uses: step-security/terraform-min-max@7c01b6babe47de9dcfdaa426c3354651299c8232 # v3.0.1
        with:
          directory: ${{ matrix.directory }}

      - name: Pre-commit Terraform ${{ steps.minMax.outputs.minVersion }}
        # Run only validate pre-commit check on min version supported
        if: ${{ matrix.directory !=  '.' }}
        uses: step-security/terraform-composite-actions/pre-commit@2eac41b76974f2ae6fd8f1ad78d51eb3bdaed7b0 # v1.14.0
        with:
          terraform-version: ${{ steps.minMax.outputs.minVersion }}
          tflint-version: ${{ env.TFLINT_VERSION }}
          args: 'terraform_validate --color=always --show-diff-on-failure --files ${{ matrix.directory }}/*'

      - name: Pre-commit Terraform ${{ steps.minMax.outputs.minVersion }}
        # Run only validate pre-commit check on min version supported
        if: ${{ matrix.directory ==  '.' }}
        uses: step-security/terraform-composite-actions/pre-commit@2eac41b76974f2ae6fd8f1ad78d51eb3bdaed7b0 # v1.14.0
        with:
          terraform-version: ${{ steps.minMax.outputs.minVersion }}
          tflint-version: ${{ env.TFLINT_VERSION }}
          args: 'terraform_validate --color=always --show-diff-on-failure --files $(ls *.tf)'

  preCommitMaxVersion:
    name: Max TF pre-commit
    runs-on:
      - runs-on
      - runner=2cpu-linux-x64
      - "run-id=${{ github.run_id }}"
    needs: collectInputs
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2
        with:
          use-policy-store: true
          api-key: ${{ secrets.GH_FRESHAENGINEERING_STEP_SECURITY_API_KEY }}

      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Terraform min/max versions
        id: minMax
        uses: step-security/terraform-min-max@7c01b6babe47de9dcfdaa426c3354651299c8232 # v3.0.1

      - name: Pre-commit Terraform ${{ steps.minMax.outputs.maxVersion }}
        uses: step-security/terraform-composite-actions/pre-commit@2eac41b76974f2ae6fd8f1ad78d51eb3bdaed7b0 # v1.14.0
        with:
          terraform-version: ${{ steps.minMax.outputs.maxVersion }}
          terraform-docs-version: ${{ env.TERRAFORM_DOCS_VERSION }}
          tflint-version: ${{ env.TFLINT_VERSION }}
