name: Release


env:
  ImageOS: ubuntu22

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - '**/*.tpl'
      - '**/*.py'
      - '**/*.tf'
      - '.github/workflows/release.yml'

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on:
      - runs-on
      - runner=2cpu-linux-x64
      - "run-id=${{ github.run_id }}"
    # Skip running release workflow on forks
    if: github.repository_owner == 'terraform-aws-modules'
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2
        with:
          use-policy-store: true
          api-key: ${{ secrets.GH_FRESHAENGINEERING_STEP_SECURITY_API_KEY }}

      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Release
        uses: step-security/semantic-release-action@874b53dfc0c44e065cbc8c3e8bc04af7b6ad69fb # v6.0.0
        with:
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git@10.0.0
            conventional-changelog-conventionalcommits@4.6.3
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
